-- ADDRESS: 서울%
-- SCORE: 리뷰 평균 점수, 소수점 세 번째 자리에서 반올림(x.xx)
-- ORDER BY: SCORE 내림차순, 즐겨찾기 수 내림차순
SELECT
        X.REST_ID, X.REST_NAME, X.FOOD_TYPE, X.FAVORITES, X.ADDRESS,
        ROUND(AVG(Y.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS X
JOIN REST_REVIEW AS Y ON X.REST_ID = Y.REST_ID
WHERE X.ADDRESS LIKE '서울%'
GROUP BY X.REST_ID
ORDER BY SCORE DESC, X.FAVORITES DESC