SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO AS i JOIN ITEM_TREE AS t ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID IN (SELECT i.ITEM_ID
    FROM ITEM_INFO AS i JOIN ITEM_TREE AS t ON i.ITEM_ID = t.ITEM_ID
    WHERE i.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;